Небольшие правки
bitrixdock/bitrixdock pull request #199
Opened 2023-12-27 19:29 UTC by Elnadrion

Главное изменение - докерфайлы с PHP перенесены в отдельную директорию, т.к. с добавлением еще и 8.3 будет бардак в корне репозитория

2023-12-27 22:38 UTC, vmpartner requested changes

2023-12-27 22:38 UTC, vmpartner commented on docker-compose.yml
> +version: "2"
Вроде сейчас вообще не нужно версию указывать

2023-12-28 10:03 UTC, Elnadrion commented on docker-compose.yml
> +version: "2"
Убрал

2023-12-31 00:10 UTC, merged

2023-12-31 00:10 UTC, vmpartner commented
🙏